### ISSUE TITLE
WARNING: Offset abs mean larger than 50

### ISSUE THREAD

**Issue by lxxcontinue** [Armstrong-lsw/SR_Self_Align#2]
When I train the B channel, I get a warning at epoch: 36, iter: 140100. At this time, the enhancement results also become very poor. Could you tell me how to solve it?

**Comment by Armstrong-lsw** [comment]
Sorry, I just saw this email now, due to busy work recently.

Because the B channel data is dirtier than other channels as you can see, We use an independent network to train it.
While, unfortunately, sometimes it still has this warning, offset larger than 50 usually means self-align failed.
So, you can just retrain the network from scratch, because of the random initialization.
